apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deployment
  namespace: static
spec:
  selector:
    matchLabels:
      app: static-dept
  replicas: 5 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: static-dept
    spec:
      containers:
      - name: static
        image: 887870046594.dkr.ecr.eu-west-2.amazonaws.com/ekandha:number
        ports:
        - containerPort: 80
